import { db } from "./db";
import { products } from "@shared/schema";

const seedProducts = [
  {
    name: "Geo Wave Graphic Tee",
    description: "Bold geometric patterns in coral and navy. Made from 100% organic cotton with a relaxed fit that's perfect for campus life. Pre-shrunk and ready to wear.",
    price: 29.99,
    originalPrice: null,
    category: "graphic",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Coral", "Navy", "White"],
    imageUrl: "/images/tshirt-geometric.png",
    badge: "Best Seller",
    inStock: true,
    rating: 4.8,
    reviewCount: 142,
  },
  {
    name: "Vintage Campus Tee",
    description: "Washed black with distressed vintage typography. This retro-inspired tee features a lived-in softness from day one. Slightly oversized cut for that effortless vibe.",
    price: 24.99,
    originalPrice: 34.99,
    category: "graphic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Washed Black", "Charcoal"],
    imageUrl: "/images/tshirt-retro.png",
    badge: "New Arrival",
    inStock: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    name: "Essential Sage Tee",
    description: "The perfect everyday basic in calming sage green. Premium heavyweight cotton with a subtle embroidered logo. Minimal design, maximum comfort.",
    price: 22.99,
    originalPrice: null,
    category: "basics",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sage", "Cream", "Slate"],
    imageUrl: "/images/tshirt-minimal.png",
    badge: "Best Seller",
    inStock: true,
    rating: 4.9,
    reviewCount: 203,
  },
  {
    name: "Festival Tie-Dye Tee",
    description: "Handmade pastel tie-dye in dreamy purple and pink gradient. Each piece is unique. Perfect for concerts, festivals, or standing out in the lecture hall.",
    price: 27.99,
    originalPrice: 39.99,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purple/Pink", "Blue/Teal"],
    imageUrl: "/images/tshirt-tiedye.png",
    badge: "New Arrival",
    inStock: true,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    name: "Classic Breton Stripe",
    description: "Timeless navy and white horizontal stripes. Premium ring-spun cotton with reinforced collar. A wardrobe essential that never goes out of style.",
    price: 26.99,
    originalPrice: null,
    category: "basics",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy/White", "Black/White", "Red/White"],
    imageUrl: "/images/tshirt-striped.png",
    badge: null,
    inStock: true,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    name: "Pop Culture Graphic Tee",
    description: "Eye-catching pop art illustration in vibrant yellow and red. Conversation starter guaranteed. Soft-touch print that won't crack or fade after washing.",
    price: 31.99,
    originalPrice: 42.99,
    category: "graphic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Yellow", "Red", "Black"],
    imageUrl: "/images/tshirt-popart.png",
    badge: "Best Seller",
    inStock: true,
    rating: 4.4,
    reviewCount: 98,
  },
  {
    name: "Dusty Rose Premium Tee",
    description: "Elevated basics in dusty rose pink. Heavyweight 240gsm cotton with a relaxed oversized silhouette. The kind of tee that looks expensive but isn't.",
    price: 28.99,
    originalPrice: null,
    category: "basics",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Dusty Rose", "Mauve", "Blush"],
    imageUrl: "/images/tshirt-dustyrose.png",
    badge: "New Arrival",
    inStock: true,
    rating: 4.8,
    reviewCount: 115,
  },
  {
    name: "Pro Mesh Athletic Tee",
    description: "Performance mesh in charcoal grey with reflective accents. Moisture-wicking, quick-dry fabric for gym sessions and weekend runs. Ergonomic cut for full range of motion.",
    price: 34.99,
    originalPrice: 44.99,
    category: "athletic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "Black", "Navy"],
    imageUrl: "/images/tshirt-athletic.png",
    badge: null,
    inStock: true,
    rating: 4.6,
    reviewCount: 78,
  },
  {
    name: "Botanical Line Art Tee",
    description: "Subtle earth-tone botanical illustrations on cream cotton. Nature-inspired minimalism for the eco-conscious student. Made from sustainably sourced organic cotton.",
    price: 25.99,
    originalPrice: 35.99,
    category: "graphic",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Sand", "Olive"],
    imageUrl: "/images/tshirt-botanical.png",
    badge: "Best Seller",
    inStock: true,
    rating: 4.7,
    reviewCount: 134,
  },
];

export async function seedDatabase() {
  const existing = await db.select().from(products);
  if (existing.length > 0) {
    return;
  }
  for (const product of seedProducts) {
    await db.insert(products).values(product);
  }
  console.log("Database seeded with", seedProducts.length, "products");
}
